config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "homes#index"
  resources :users
  resources :events do
    resources :event_attendings
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
require 'date'
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User"
    has_many :event_attendings, foreign_key: :attended_event_id, dependent: :destroy
    has_many :attendees, through: :event_attendings, source: :event_attendee
    has_many :invitations

    validates :title, presence: true
    validates :body, presence: true
    validates :date, presence: true
    validates :location, presence: true

    scope :past, -> { where(date: ...Date.today) }

   scope :future, -> { where(date: Date.today..) }
end

app/models/event_attending.rb
class EventAttending < ApplicationRecord
    belongs_to :attended_event, class_name: "Event"
    belongs_to :event_attendee, class_name: "User"
end

app/models/guest_inviting.rb
class GuestInviting < ApplicationRecord
    belongs_to :guest_invited, class_name: "User"
    belongs_to :guesting_invitation, class_name: "Invitation"
end

app/models/invitation.rb
class Invitation < ApplicationRecord
    belongs_to :event
    belongs_to :host, class_name: "User"
    has_many :guest_invitings, foreign_key: :guesting_invitation_id
    has_many :guests, through: :guest_invitings, source: :guest_invited
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: "creator_id", class_name: "Event"
  has_many :event_attendings, foreign_key: :event_attendee_id
  has_many :attended_events, through: :event_attendings
  has_many :hosting_invitations, foreign_key: :host_id, class_name: "Event"
  has_many :guest_invitings, foreign_key: :guest_invited_id
  has_many :guesting_invitations, through: :guest_invitings
  
  validates :username, presence: true,uniqueness: true, length: { minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
    end
end

app/controllers/event_attendings_controller.rb
class EventAttendingsController < ApplicationController
  def index
    @event_attendings = EventAttending.all
  end

  def new
    @event_attending = EventAttending.new
  end

  def create
    @event = Event.find(params[:event_id])
    @event_attending = @event.event_attendings.create(event_attending_params)

    if @event_attending.save
      redirect_to event_path(@event.id), notice: "You are successfully listed as an attendee for #{@event.title}."
    else
      redirect_to events_path, status: :unprocessable_entity
    end
  end

  def destroy
    @event_attending = EventAttending.find_by(attended_event_id: params[:event_id], event_attendee_id: current_user.id)
    @event_attending.destroy

    redirect_to root_path, status: :see_other, notice: "You have been removed from #{@event_attending.attended_event.title} list of attendees."
  end

  def event_attending_params
    params.require(:event_attending).permit(:attended_event_id,:event_attendee_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:new,:index]

  def index
      @events = Event.all
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @user = User.find(current_user.id)

    @event = @user.created_events.build(event_params)

    if @event.save
      redirect_to user_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to root_path, status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    
    redirect_to root_path, status: :see_other
  end

  private
  def event_params
    params.require(:event).permit(:title,:body,:date,:location,:creator_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendings_helper.rb
module EventAttendingsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_attendings/_form.html.erb
<%= form_with model: [@event,@event.event_attendings.build] do |f| %>
<div>
    <%= f.hidden_field :attended_event_id, value: "#{@event.id}" %>
</div>

<div>
    <%= f.hidden_field :event_attendee_id, value: "#{current_user.id}" %>
</div>

<div> <%= f.submit "Attend event" %> </div>

<% end %>

app/views/event_attendings/index.html.erb
<h1>EventAttendings#index</h1>
<p>Find me in app/views/event_attendings/index.html.erb</p>

app/views/event_attendings/new.html.erb
<%= render "form"%>

app/views/events/_form.html.erb
<%= form_with model: @event do |f| %>
<div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <% @event.errors.full_messages_for(:title).each do |message| %>
    <div> <%= message %> </div>
    <% end %>
</div>

<div>
    <%= f.label :body %><br>
    <%= f.text_field :body %>
    <% @event.errors.full_messages_for(:body).each do |message|%>
    <div> <%= message %></div>
    <% end %>
</div>

<div>
    <%= f.label :date %><br>
    <%= f.date_field :date %>
    <% @event.errors.full_messages_for(:date).each do |message|%>
    <div> <%= message %></div>
    <% end %>
</div>

<div>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
    <% @event.errors.full_messages_for(:location).each do |message|%>
    <div> <%= message %></div>
    <% end %>
</div>

<div>
    <%= f.hidden_field :user_id, value: "#{current_user.id}" %>
    <% @event.errors.full_messages_for(:user_id).each do |message|%>
    <div> <%= message %></div>
    <% end %>
</div>

<div> <%= f.submit %> </div>

<% end %>

app/views/events/edit.html.erb
<h1> Edit Event: <h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<h1>Events</h1>

<h2> Past events </h2>
<ul>
<% @events.past.each do |e| %>
    <li><%= e.title %></li>
    <strong><%= e.date %></strong>
<% end %>
</ul>

<h2> Future events </h2>
<ul>
<% @events.future.each do |e| %>
    <li><%= e.title %></li>
    <strong><%= e.date %></strong>
    <div><%= link_to "See event", event_path(e) %></div><br>
<% end %>
</ul>

<%= link_to "Back to home", root_path %>

app/views/events/new.html.erb
<h1> New Event: <h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<div><%= @event.creator.username %></div>
<div><%= @event.date %></div>
<div><%= @event.location %></div>
<strong> Attendees </strong>
<ul>
<div><% @event.attendees.each do |a| %></div>
        <li><%= a.username %></li>
    <% end %>
</ul>
<% if Event.future && !@event.attendees.include?(current_user) %>
    <div><%= render "event_attendings/form"%></div><br>
<% end %>

<div><%= link_to "Back to home", root_path%></div>

app/views/homes/index.html.erb
<h1>Home</h1>

<% if user_signed_in?%>
    <div><%= link_to "My events", user_path(current_user)%></div><br>
    <div><%= link_to "Create event", new_event_path%></div><br>
    <div><%= link_to "See available events", events_path%></div><br>
    <div><%= button_to "Sign out", destroy_user_session_path, method: :delete %></div>
<% else %>
    <div><%= link_to "Sign up", new_user_registration_path%></div>
    <div><%= link_to "Log in", new_user_session_path%></div>
    <div><%= link_to "See available events", events_path%></div><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/users/index.html.erb
<% @users.each do |u|%>
    <li><%= u.username %></li><br>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s events</h1>

<div><% @user.created_events.each do |e| %></div>
    <h2>Event</h2>
    <div><%= e.title %></div>
    <div><%= e.body %></div>
    <strong><%= e.date %></strong>
    <div><%= e.location %></div>
    <div><%= link_to "Edit event", edit_event_path(e.id) %>
    <div><%= link_to "Delete event", event_path(e), data: { turbo_method: :delete,
                                                            turbo_confirm: "Are you sure?"
                                                            } %>
    <% end %>


<h2> Events attended</h2>
<ul>
<div><% @user.attended_events.past.each do |e| %></div>
    <li><%= e.title %></li>
    <div><%= e.date %></div><br>
<% end %>
</ul>

<h2> Events to attend</h2>
<ul>
<div><% @user.attended_events.future.each do |e| %></div>
    <li><%= e.title %></li>
    <div><%= e.date %></div><br>
    <div><%= link_to "Will not go", event_event_attending_path(e), data: { turbo_method: :delete,
                                                                           turbo_confirm: "Are you sure?"
                                                                         } %>
<% end %>
</ul>

<div><%= link_to "Back to home", root_path%></div>